2021-09-15_11-19-41 [http-nio-8084-exec-1] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.USERS(ID) [1, 'password@admin', 'admin']"; SQL statement:
insert into users (password, user_name, id) values (?, ?, ?) [23505-200]
2021-09-15_11-19-41 [http-nio-8084-exec-1] ERROR c.c.a.e.GlobalExceptionHandler - could not execute statement; SQL [n/a]; constraint ["PRIMARY KEY ON PUBLIC.USERS(ID) [1, 'password@admin', 'admin']"; SQL statement:
insert into users (password, user_name, id) values (?, ?, ?) [23505-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
2021-09-15_11-22-50 [http-nio-8084-exec-2] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.USERS(ID) [1, 'password@admin', 'admin']"; SQL statement:
insert into users (password, user_name, id) values (?, ?, ?) [23505-200]
2021-09-15_11-22-50 [http-nio-8084-exec-2] ERROR c.c.a.e.GlobalExceptionHandler - Bad Credentials
2021-09-15_11-22-50 [http-nio-8084-exec-10] ERROR c.c.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2021-09-15_15-25-19 [http-nio-8084-exec-2] ERROR c.c.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2021-09-15_15-25-19 [http-nio-8084-exec-6] ERROR c.c.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2021-09-15_15-25-19 [HikariPool-4 connection adder] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-4 - Error thrown while acquiring connection from data source
org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database is open in exclusive mode; can not open additional connections [90135-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.engine.Session.checkSuspended(Session.java:1369)
	at org.h2.engine.Session.isOpen(Session.java:1303)
	at org.h2.engine.Session.waitIfExclusiveModeEnabled(Session.java:1639)
	at org.h2.command.Command.executeQuery(Command.java:186)
	at org.h2.jdbc.JdbcConnection.isReadOnly(JdbcConnection.java:631)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:402)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-09-15_15-31-25 [http-nio-8084-exec-1] ERROR c.c.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2021-09-15_15-31-25 [http-nio-8084-exec-2] ERROR c.c.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2021-09-15_15-38-24 [http-nio-8084-exec-3] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.USERS(ID) [1, 'password@admin', 'admin']"; SQL statement:
insert into users (password, user_name, id) values (?, ?, ?) [23505-200]
2021-09-15_15-38-24 [http-nio-8084-exec-3] ERROR c.c.a.e.GlobalExceptionHandler - Bad Credentials
2021-09-15_15-38-24 [http-nio-8084-exec-6] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.USERS(ID) [2, 'password@pandey', 'Uddeshay Pandey']"; SQL statement:
insert into users (password, user_name, id) values (?, ?, ?) [23505-200]
2021-09-15_15-38-24 [http-nio-8084-exec-6] ERROR c.c.a.e.GlobalExceptionHandler - Bad Credentials
